export interface Menu {
  id: number;
  nombreProducto: string;
  descripcion?: string;
  precio: number;
  imagen?: string;
  categoriaId?: number;
  negocioId: number;
}

export const menusList: Menu[] = [
  {
    id: 1,
    nombreProducto: "Hamburguesa",
    descripcion: "Hamburguesa con queso y tocino",
    precio: 99.99,
    imagen: "hamburguesa.jpg",
    categoriaId: 1,
    negocioId: 1,
  },
  {
    id: 2,
    nombreProducto: "Pizza",
    descripcion: "Pizza de peperoni con extra queso",
    precio: 150.00,
    imagen: "pizza.jpg",
    categoriaId: 1,
    negocioId: 1,
  },
  {
    id: 3,
    nombreProducto: "Hot Dog",
    descripcion: "Hot dog clásico con mostaza y ketchup",
    precio: 45.50,
    imagen: "hotdog.jpg",
    categoriaId: 1,
    negocioId: 1,
  },
  {
    id: 4,
    nombreProducto: "Tacos",
    descripcion: "Tacos al pastor con cebolla y cilantro",
    precio: 35.00,
    imagen: "tacos.jpg",
    categoriaId: 1,
    negocioId: 2,
  },
  {
    id: 5,
    nombreProducto: "Ensalada",
    descripcion: "Ensalada fresca con aderezo balsámico",
    precio: 50.00,
    imagen: "ensalada.jpg",
    categoriaId: 1,
    negocioId: 2,
  },

  // Categoría 2: Ropa
  {
    id: 6,
    nombreProducto: "Camiseta Básica",
    descripcion: "Camiseta de algodón en varios colores",
    precio: 200.00,
    imagen: "camiseta.jpg",
    categoriaId: 2,
    negocioId: 3,
  },
  {
    id: 7,
    nombreProducto: "Jeans",
    descripcion: "Jeans de mezclilla ajustados",
    precio: 350.00,
    imagen: "jeans.jpg",
    categoriaId: 2,
    negocioId: 3,
  },
  {
    id: 8,
    nombreProducto: "Chaqueta de Cuero",
    descripcion: "Chaqueta de cuero para clima frío",
    precio: 600.00,
    imagen: "chaqueta.jpg",
    categoriaId: 2,
    negocioId: 4,
  },
  {
    id: 9,
    nombreProducto: "Zapatos Deportivos",
    descripcion: "Zapatos cómodos para hacer ejercicio",
    precio: 800.00,
    imagen: "zapatos_deportivos.jpg",
    categoriaId: 2,
    negocioId: 4,
  },
  {
    id: 10,
    nombreProducto: "Sombrero de Sol",
    descripcion: "Sombrero de paja para el verano",
    precio: 150.00,
    imagen: "sombrero.jpg",
    categoriaId: 2,
    negocioId: 5,
  },

  // Categoría 3: Electrónica
  {
    id: 11,
    nombreProducto: "Smartphone",
    descripcion: "Smartphone de última generación con cámara de 48MP",
    precio: 12000.00,
    imagen: "smartphone.jpg",
    categoriaId: 3,
    negocioId: 3,
  },
  {
    id: 12,
    nombreProducto: "Laptop Gaming",
    descripcion: "Laptop potente para juegos con tarjeta gráfica RTX",
    precio: 25000.00,
    imagen: "laptop_gaming.jpg",
    categoriaId: 3,
    negocioId: 7,
  },
  {
    id: 13,
    nombreProducto: "Smartwatch",
    descripcion: "Smartwatch con monitor de ritmo cardíaco y GPS",
    precio: 4000.00,
    imagen: "smartwatch.jpg",
    categoriaId: 3,
    negocioId: 8,
  },
  {
    id: 14,
    nombreProducto: "Auriculares Inalámbricos",
    descripcion: "Auriculares de calidad superior con cancelación de ruido",
    precio: 1500.00,
    imagen: "auriculares.jpg",
    categoriaId: 3,
    negocioId: 9,
  },
  {
    id: 15,
    nombreProducto: "Cámara Digital",
    descripcion: "Cámara digital con lente intercambiable",
    precio: 8000.00,
    imagen: "camara_digital.jpg",
    categoriaId: 3,
    negocioId: 9,
  },

  // Categoría 4: Hogar
  {
    id: 16,
    nombreProducto: "Sofá Cama",
    descripcion: "Sofá cama de 3 plazas con colchón viscoelástico",
    precio: 5000.00,
    imagen: "sofa.jpg",
    categoriaId: 4,
    negocioId: 10,
  },
  {
    id: 17,
    nombreProducto: "Mesa de Comedor",
    descripcion: "Mesa de comedor de madera para 6 personas",
    precio: 2500.00,
    imagen: "mesa_comedor.jpg",
    categoriaId: 4,
    negocioId: 10,
  },
  {
    id: 18,
    nombreProducto: "Lámpara de Techo",
    descripcion: "Lámpara moderna para salón de 3 luces",
    precio: 800.00,
    imagen: "lampara_techo.jpg",
    categoriaId: 4,
    negocioId: 11,
  },
  {
    id: 19,
    nombreProducto: "Cortinas Roller",
    descripcion: "Cortinas opacas para control de luz",
    precio: 600.00,
    imagen: "cortinas.jpg",
    categoriaId: 4,
    negocioId: 12,
  },
  {
    id: 20,
    nombreProducto: "Mueble de TV",
    descripcion: "Mueble para TV con espacio de almacenamiento",
    precio: 1500.00,
    imagen: "mueble_tv.jpg",
    categoriaId: 4,
    negocioId: 12,
  },

  // Categoría 5: Deportes
  {
    id: 21,
    nombreProducto: "Pelota de Fútbol",
    descripcion: "Pelota de fútbol profesional para entrenamientos",
    precio: 350.00,
    imagen: "pelota_futbol.jpg",
    categoriaId: 5,
    negocioId: 13,
  },
  {
    id: 22,
    nombreProducto: "Raqueta de Tenis",
    descripcion: "Raqueta ligera de tenis para principiantes",
    precio: 800.00,
    imagen: "raqueta_tenis.jpg",
    categoriaId: 5,
    negocioId: 13,
  },
  {
    id: 23,
    nombreProducto: "Zapatillas de Running",
    descripcion: "Zapatillas de running con amortiguación avanzada",
    precio: 1200.00,
    imagen: "zapatillas_running.jpg",
    categoriaId: 5,
    negocioId: 14,
  },
  {
    id: 24,
    nombreProducto: "Balón de Baloncesto",
    descripcion: "Balón de baloncesto oficial de la NBA",
    precio: 500.00,
    imagen: "balon_basket.jpg",
    categoriaId: 5,
    negocioId: 14,
  },
  {
    id: 25,
    nombreProducto: "Equipo de Yoga",
    descripcion: "Kit de yoga con mat, bloque y correa",
    precio: 600.00,
    imagen: "equipo_yoga.jpg",
    categoriaId: 5,
    negocioId: 15,
  },
];
